// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type SocialConnection struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Provider  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	GoogleID  string
	Email     string
	CreatedAt pgtype.Timestamp
}
