// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package store

import (
	"context"
)

const createNewPosts = `-- name: CreateNewPosts :one
INSERT INTO posts (title, content)
VALUES ($1, $2)
  RETURNING id, title, content, created_at, updated_at
`

type CreateNewPostsParams struct {
	Title   string
	Content string
}

func (q *Queries) CreateNewPosts(ctx context.Context, arg CreateNewPostsParams) (Post, error) {
	row := q.db.QueryRow(ctx, createNewPosts, arg.Title, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
