// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publisher.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchPendingJobs = `-- name: FetchPendingJobs :many
SELECT id, user_id, post_id, status, scheduled_at, created_at, updated_at FROM publishers
WHERE status = 'pending'
  AND scheduled_at <= NOW()
ORDER BY scheduled_at ASC
FOR UPDATE SKIP LOCKED
LIMIT 50
`

func (q *Queries) FetchPendingJobs(ctx context.Context) ([]Publisher, error) {
	rows, err := q.db.Query(ctx, fetchPendingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publisher
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PostID,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobAsCompleted = `-- name: UpdateJobAsCompleted :exec
UPDATE publishers
SET status = 'completed',
    published_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateJobAsCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateJobAsCompleted, id)
	return err
}

const updateJobAsFailed = `-- name: UpdateJobAsFailed :exec
UPDATE publishers
SET status = 'failed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateJobAsFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateJobAsFailed, id)
	return err
}

const updateJobAsProcessing = `-- name: UpdateJobAsProcessing :exec
UPDATE publishers
SET status = 'processing',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateJobAsProcessing(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateJobAsProcessing, id)
	return err
}
