// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publisher.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPublisherJob = `-- name: CreatePublisherJob :many
INSERT INTO publisher (post_id, user_id, social_connection_id, status)
SELECT $1, $2, sc_id, 'pending'
FROM unnest($3::uuid[]) AS sc_id
RETURNING id, post_id, user_id, social_connection_id, status, created_at, updated_at
`

type CreatePublisherJobParams struct {
	PostID  pgtype.UUID
	UserID  pgtype.UUID
	Column3 []pgtype.UUID
}

func (q *Queries) CreatePublisherJob(ctx context.Context, arg CreatePublisherJobParams) ([]Publisher, error) {
	rows, err := q.db.Query(ctx, createPublisherJob, arg.PostID, arg.UserID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publisher
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.SocialConnectionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishersByPostID = `-- name: GetPublishersByPostID :many
SELECT id, post_id, user_id, social_connection_id, status, created_at, updated_at FROM publisher
WHERE post_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetPublishersByPostID(ctx context.Context, postID pgtype.UUID) ([]Publisher, error) {
	rows, err := q.db.Query(ctx, getPublishersByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publisher
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.SocialConnectionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublisherAsCompleted = `-- name: UpdatePublisherAsCompleted :exec
UPDATE publisher
SET status = 'completed',
    publisher_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdatePublisherAsCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updatePublisherAsCompleted, id)
	return err
}

const updatePublisherAsFailed = `-- name: UpdatePublisherAsFailed :exec
UPDATE publisher
SET status = 'failed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdatePublisherAsFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updatePublisherAsFailed, id)
	return err
}
