// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConnectNewProvider(ctx context.Context, arg ConnectNewProviderParams) (SocialConnection, error)
	CreateNewPosts(ctx context.Context, arg CreateNewPostsParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FetchPendingJobs(ctx context.Context) ([]Publisher, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	UpdateJobAsCompleted(ctx context.Context, id pgtype.UUID) error
	UpdateJobAsFailed(ctx context.Context, id pgtype.UUID) error
	UpdateJobAsProcessing(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
