// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	ConnectNewProvider(ctx context.Context, arg ConnectNewProviderParams) (SocialConnection, error)
	CreateNewPosts(ctx context.Context, arg CreateNewPostsParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
}

var _ Querier = (*Queries)(nil)
