// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: socials_connections.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const connectNewProvider = `-- name: ConnectNewProvider :one
INSERT INTO social_connections (
  user_id,
  provider,
  provider_user_id,
  access_token,
  refresh_token,
  expires_at
)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at, updated_at
`

type ConnectNewProviderParams struct {
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	AccessToken    string
	RefreshToken   pgtype.Text
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) ConnectNewProvider(ctx context.Context, arg ConnectNewProviderParams) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, connectNewProvider,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByUserID = `-- name: GetProviderByUserID :many
SELECT
   id,
   user_id,
   provider_user_id,
   created_at
FROM social_connections
WHERE user_id = $1
ORDER BY created_at ASC
`

type GetProviderByUserIDRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ProviderUserID string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetProviderByUserID(ctx context.Context, userID uuid.UUID) ([]GetProviderByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getProviderByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProviderByUserIDRow
	for rows.Next() {
		var i GetProviderByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
