// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: socials_connections.sql

package store

import (
	"context"
)

const connectNewProvider = `-- name: ConnectNewProvider :one
INSERT INTO social_connections (provider)
VALUES($1)
RETURNING id, provider, created_at, updated_at
`

func (q *Queries) ConnectNewProvider(ctx context.Context, provider string) (SocialConnection, error) {
	row := q.db.QueryRow(ctx, connectNewProvider, provider)
	var i SocialConnection
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
