// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, email)
VALUES($1, $2)
RETURNING id, google_id, email, created_at
`

type CreateUserParams struct {
	GoogleID string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.GoogleID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, created_at FROM USERS
WHERE email = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
